"use client";

import { useEffect, useState } from "react";
import { IndianRupee, TrendingUp, Clock, Wallet } from "lucide-react";

interface RevenueData {
    totalCollected: number;
    timeSavedHours: number;
}

export function RevenueImpact() {
    const [data, setData] = useState<RevenueData | null>(null);

    useEffect(() => {
        fetch("/api/dashboard/automation")
            .then(res => res.json())
            .then(res => setData(res.revenue))
            .catch(console.error);
    }, []);

    return (
        <div className="rounded-3xl bg-gradient-to-br from-emerald-500 to-teal-600 p-6 text-white shadow-lg shadow-emerald-500/20">
            <div className="flex items-center gap-3 mb-6">
                <div className="h-10 w-10 rounded-xl bg-white/20 flex items-center justify-center backdrop-blur-sm">
                    <Wallet className="h-5 w-5 text-white" />
                </div>
                <div>
                    <h3 className="font-bold text-lg leading-tight">Revenue Impact</h3>
                    <p className="text-emerald-100 text-xs">Generated by autopilot</p>
                </div>
            </div>

            <div className="space-y-6">
                <div>
                    <p className="text-emerald-100 text-sm font-medium">Total Collected (Auto)</p>
                    <div className="flex items-baseline gap-1">
                        <span className="text-3xl font-bold">₹{(data?.totalCollected || 0).toLocaleString()}</span>
                    </div>
                </div>

                <div className="grid grid-cols-2 gap-4">
                    <div className="bg-white/10 rounded-xl p-3 backdrop-blur-sm">
                        <div className="flex items-center gap-1.5 text-emerald-100 mb-1">
                            <Clock className="h-3.5 w-3.5" />
                            <span className="text-xs font-medium">Time Saved</span>
                        </div>
                        <p className="text-lg font-semibold">{data?.timeSavedHours || 0} hrs</p>
                    </div>
                    <div className="bg-white/10 rounded-xl p-3 backdrop-blur-sm">
                        <div className="flex items-center gap-1.5 text-emerald-100 mb-1">
                            <TrendingUp className="h-3.5 w-3.5" />
                            <span className="text-xs font-medium">Faster Pay</span>
                        </div>
                        <p className="text-lg font-semibold">42%</p>
                    </div>
                </div>
            </div>

            <div className="mt-6 pt-6 border-t border-white/10">
                <p className="text-xs text-emerald-100 leading-relaxed">
                    &quot;Automation has effectively unlocked <span className="font-bold text-white">₹{((data?.totalCollected || 0) * 0.15).toLocaleString()}</span> in cash flow that would have been late.&quot;
                </p>
            </div>
        </div>
    );
}
